swiftmailer:
    # url: '%env(MAILER_URL)%'
    # spool: { type: 'memory' }
    transport: smtp
    auth_mode: login
    encryption: ssl
    port: 465
    host: smtp.gmail.com
    username: orientationauthentique@gmail.com
    password: 404#@gbo
    spool: { type: 'memory' }
