<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpNSM7K\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpNSM7K/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOpNSM7K.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerOpNSM7K\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerOpNSM7K\srcProdProjectContainer(array(
    'container.build_hash' => 'OpNSM7K',
    'container.build_id' => '274d4bab',
    'container.build_time' => 1544368912,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpNSM7K');
